Monhelper: handle 2 common situations that would previously lead to exceptions
1) When suponoff asks for PID 0 because of stopped processes
2) When suponoff asks for a PID that has just been stopped

Handling these two situation reduces clutter in the program's output that
may prevent one from detecting and managing real excteptions.

stopped and the suponoff app asks for PID 0

2016-11-26 12:06:03,614 ERROR suponoff-monhelper.py:50 Process 0:
Traceback (most recent call last):
...
...
FileNotFoundError: [Errno 2] No such file or directory: '/proc/0/stat'

RPC call:

POST /RPC2 HTTP/1.1
Host: localhost:9002
Accept-Encoding: gzip
Content-Type: text/xml
User-Agent: Python-xmlrpc/3.5
Content-Length: 475

<?xml version='1.0'?>
<methodCall>
<methodName>getProcessResourceUsage</methodName>
<params>
<param>
<value><array><data>
<value><int>26232</int></value>
<value><int>26231</int></value>
<value><int>26234</int></value>
<value><int>26233</int></value>
<value><int>0</int></value>
<value><int>0</int></value>
<value><int>0</int></value>
<value><int>0</int></value>
<value><int>0</int></value>
<value><int>0</int></value>
</data></array></value>
</param>
</params>
</methodCall>

2016-11-26 17:18:19,787 ERROR suponoff-monhelper.py:85 Error
Traceback (most recent call last):
...
...
FileNotFoundError: [Errno 2] No such file or directory: '/proc/32336/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
...
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=32336)